os:
  - osx
  - windows
  - linux

dist: bionic

language: rust
rust:
  - stable
  - 1.41.0

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]] && [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
    cargo install cargo-tarpaulin
  fi

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo clean
  - cargo clippy -- -D warnings
  - cargo build
  - cargo test --verbose

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]] && [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
