[package]
name = "rusty-mancala"
version = "0.1.0"
authors = ["loganballard <loganballard@gmail.com>", "Belén <rooneyshuman>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.0"
serde = { version = "1.0", features = ["derive"] }
simple_logger = "1.6.0"
log = "*"
